keycloak:
  auth:
    adminUser: admin

  service:
    type: NodePort

  postgresql:
    enabled: false

  externalDatabase:
    host: postgres-chart-postgresql
    user: postgres
    password:
    database: keycloak
