keycloak:
  auth:
    adminUser: admin

  service:
    type: NodePort

  postgresql:
    enabled: false

  externalDatabase:
    host: postgres-chart-postgresql
    user: postgres
    password:
    database: keycloak

  image:
    debug: true

  livenessProbe:
    initialDelaySeconds: 500
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1

