apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: NodePort
  selector:
    app: ledger-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081