apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  BPL_JVM_THREAD_COUNT: "10"

  RECORDER_URL: "{{.Values.recorderUrl}}"

  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: "{{.Values.keycloak.issuerUri}}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-ID: "{{.Values.keycloak.clientId}}"

  LOGIN_REDIRECT: "{{.Values.loginRedirect}}"

  SPRING_REDIS_HOST: "{{.Values.redis.host}}"
