apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
        - name: connect-contentainer
          image: debezium/connect
          ports:
            - containerPort: 8083
              name: web
          env:
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: "ledger_configs"
            - name: OFFSET_STORAGE_TOPIC
              value: "ledger_offsets"
            - name: STATUS_STORAGE_TOPIC
              value: "ledger_statuses"
            - name: BOOTSTRAP_SERVERS
              value: "{{.Values.kafkaUrl}}"
          readinessProbe:
            httpGet:
              port: 8083
              path: /
            initialDelaySeconds: 2
            failureThreshold: 10

