apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: web-contentainer
          image: provectuslabs/kafka-ui
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-chart:9092
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka-chart
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 2
            failureThreshold: 10

