apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ledger-ingress-new
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: recorder-service
              servicePort: 8080