apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ledger-ingress-new-gce
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{.Values.externalAddress}}
    networking.gke.io/managed-certificates: ledger-web
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: {{.Values.services.web}}
      http:
        paths:
          - path: /*
            backend:
              serviceName: recorder-service
              servicePort: 8080