apiVersion: v1
kind: Service
metadata:
  name: ledger-recorder-service
spec:
  type: ClusterIP
  selector:
    app: ledger-recorder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080