name: Deploy ledger gateway
on:
  repository_dispatch:
    types: [ledger-gateway-released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - id: get-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: ledger-k8s
        location: europe-west6-a
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Deploy'
      uses: elseu/sdu-helm-deploy-action@0.0.5
      with:
        helm: 'helm3'
        release: 'gateway-chart'
        namespace: 'ledger'
        chart: 'k8s/ledger_gateway'
        token: '${{ github.token }}'
        values: |
          image:
            tag: "${{ github.event.client_payload.version }}${{ github.event.inputs.version }}"
          keycloak:
            clientSecret: "${{ secrets.KEYCLOAK_CLIENT_SECRET }}"

